### ISSUE TITLE
Login validation

### ISSUE THREAD

**Issue by John-MBDP** [TheBinaryGuy/next-hono-lucia#3]
I’m getting inconsistent behaviour when trying to log in to a validated user account

Steps to reproduce:

1. Follow the workflow to create an account
2. Login using the created account

Expected Behaviour: When the login button is clicked, the user should see the logout button

Current Behaviour: When trying to log in to a validated user account, there is an inconsistency where a user is not being validated and is prompting the user to log in again

https://github.com/user-attachments/assets/ceaa0d19-4978-44dc-826d-e7e1b392d9dc

**Comment by TheBinaryGuy** [comment]
This is because of the client side router cache (if you hard refresh it shows the logged in state button). Works perfectly fine with Next 15 - latest canary as they have disabled all the caching on their side.

To [fix](https://github.com/TheBinaryGuy/next-hono-lucia/commit/3eca71d53a3d57bc666179e9f4fa030998166161) this in Next 14, replace this in `src/app/(auth)/login/login-form.tsx` (inside `onSuccess`):

```ts
// push(Routes.home());
window.location.assign(Routes.home());
```

Basically this performs a full page reload, so the client side cache gets busted.

Ideally in a real app, this is not a big deal, as you probably should redirect to a dashboard of sorts after logging in (and also call `revalidatePath('/')` inside the login server route), and even when they go back to the dashboard the client side cache expires by then.

P.S.: `revalidatePath('/')` in login server route doesn't do anything in this case as it doesn't immediately invalidate the router cache, I think it only does that in a server action.

---

I even tried disabling all the caching on the home page like this (without any luck):

```ts
export const revalidate = 0;
export const dynamic = 'force-dynamic';
export const fetchCache = 'default-no-store';
```

All in all, Next 14 sucks with all the default caching. Hopefully, Next 15 comes out soon.

Next 15 Canary (v73) with no weird default caching:

https://github.com/user-attachments/assets/01063b91-6112-49b0-87e0-5eaff26d333d

**Comment by TheBinaryGuy** [comment]
Also, thanks for catching all these issues and edge cases :)

**Comment by John-MBDP** [comment]
No worries! Yeah, I figured it had to do something with caching, In my previous projects, I'd normally do revalidate/redirect. Thanks for the prompt response! I'll close this.
